services:
  postgres:
    image: postgres:17-alpine
    container_name: dbindex-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    container_name: dbindex-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: testdb
      MYSQL_USER: dbcooper
      MYSQL_PASSWORD: dbcooper
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "dbcooper", "--password=dbcooper" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mariadb:
    image: mariadb:11.4
    container_name: dbindex-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: testdb
      MARIADB_USER: dbcooper
      MARIADB_PASSWORD: dbcooper
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: dbindex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: dbindex-clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_DB: default
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--query", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:8.0
    container_name: dbindex-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbcooper
      MONGO_INITDB_ROOT_PASSWORD: dbcooper
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--username", "dbcooper", "--password", "dbcooper", "--authenticationDatabase", "admin", "--eval", "db.adminCommand({ping:1})" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
  mysql_data:
  mariadb_data:
  mongodb_data:
